## Manipulação de Strings com Python


>  Uma variavel primaria de texto é chamda de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracters ultilizamos um objeto, ou variaveis compostas no caso da maioria das linguagens chamda string. Vamos ver como aplica.  

In [60]:
frase = "boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

boa tarde a todos
boa tarde


In [61]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [62]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [63]:
print(len(frase))
print(len(saudacao))

17
9


In [64]:
frase = frase.replace('a todos', 'galerinha!')
print(frase)
saudacao = saudacao.replace('tarde', 'noite')
print(saudacao)

boa tarde galerinha!
boa noite


In [65]:
frase = [i for i in frase]
print(frase)

['b', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [66]:
for x  in frase:
    print(x)

b
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


### Exercício 1:
> Crie um código para a seguinte frase: "Sabia que o sabiá sabia assombiar" reparticionando por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [67]:
frase = "Sabia que o sabiá sabia assobiar"
palavras = frase.split()
print(palavras)
for i in range(max(len(x) for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end=' ')

    print()


['Sabia', 'que', 'o', 'sabiá', 'sabia', 'assobiar']
S q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


In [68]:
for i in range(max(len(x) for x in palavras)):
    print(' '.join(x[i] if i < len(x) else' ' for x in palavras))

S q o s s a
a u   a a s
b e   b b s
i     i i o
a     á a b
          i
          a
          r


## Introdução a NumPy
> NumPy é  um biblioteca python para desenvolvimento de matrizes. Tem por objetivos facilitar na criação de algoritmos matematicos para solucionar paradgimas avançados em relação a arrays.

In [69]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [70]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [71]:
b = np.array([(1,2,3), (4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [72]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [73]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [74]:
print(a.max())
print(b.max())
print(c.max())
print(d.max())

3
6
1.0
1.0


In [75]:
print(a.min())
print(b.min())
print(c.min())
print(d.min())

1
1
1.0
0.0


In [77]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


In [78]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


> Para desvio padrão

In [80]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
1.71
0.0
0.4


In [94]:
e = np.append((),0)
print(e)

[0.]


## Exercício 2:
> Crie uma matriz chamada contar com os numeros de  0 ate 9. Ao final crie uma contagem, media e desvio padrao dessa matriz. Para adcionar de zero a 9 ultilize um for e depois atribua á matriz. 